# Generated by Django 5.0.6 on 2024-08-18 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0004_item_batch_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(null=True, unique=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('scan_type', models.CharField(max_length=100, null=True)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('in_employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.store_employee')),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.item')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.qr_code')),
            ],
        ),
    ]
