# Generated by Django 5.0.6 on 2024-08-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_item',
            old_name='in_employee',
            new_name='store_employee',
        ),
    ]
