# Generated by Django 5.0.6 on 2024-08-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_item_batch_qr_code'),
        ('store', '0002_rename_in_employee_in_item_store_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('verify_status', models.IntegerField(max_length=100, null=True)),
                ('verify_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('store_employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.store_employee')),
                ('verify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='office.office_employee')),
            ],
        ),
    ]
