# Generated by Django 5.0.6 on 2024-08-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_item_batch_qr_code'),
        ('store', '0003_voucher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(null=True, unique=True)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('verify_status', models.IntegerField(default=0, null=True)),
                ('verify_date', models.DateTimeField(null=True)),
                ('scan_type', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.item')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.qr_code')),
                ('store_employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.store_employee')),
                ('verify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='office.office_employee')),
                ('voucher', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='store.voucher_name')),
            ],
        ),
    ]
