# Generated by Django 5.0.6 on 2024-08-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Office_employee',
        ),
    ]
