# Generated by Django 5.0.2 on 2024-02-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('paking', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('gst', models.FloatField(default=0)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
