# Generated by Django 5.0.2 on 2024-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
