# Generated by Django 5.0.2 on 2024-02-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_add_product_stock_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.product')),
            ],
        ),
    ]
