# Generated by Django 5.0.2 on 2024-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_sell_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
