# Generated by Django 5.0.2 on 2024-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_add_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
