# Generated by Django 5.0.2 on 2024-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_stock_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_shope_name', models.CharField(max_length=100)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_mobile', models.IntegerField()),
                ('dealer_email', models.CharField(max_length=100)),
                ('dealer_address', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('aadhar_card_number', models.IntegerField(default=True)),
                ('pan_card_number', models.CharField(default=True, max_length=100)),
                ('gst_number', models.CharField(default=True, max_length=100)),
                ('added_by', models.CharField(default=True, max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
