# Generated by Django 5.0.2 on 2024-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_dealer_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_registration',
            name='aadhar_card_number',
            field=models.IntegerField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='gst_number',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer_registration',
            name='pan_card_number',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_mobile',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
