# Generated by Django 5.0.2 on 2024-02-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_alter_dealer_registration_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealer_registration',
            new_name='Dealer',
        ),
    ]
