# Generated by Django 5.0.2 on 2024-02-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_rename_dealer_registration_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='added_by',
        ),
        migrations.AddField(
            model_name='dealer',
            name='employee',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee'),
        ),
    ]
