# Generated by Django 5.0.2 on 2024-03-05 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_dealer_admin_alter_dealer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='dealer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.dealer'),
        ),
    ]
