# Generated by Django 5.0.2 on 2024-03-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_alter_sell_product_dealer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='dealer_email',
            new_name='loction',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='aadhar_card_number',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='pan_card_number',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='state_name',
        ),
    ]
