# Generated by Django 5.0.2 on 2024-03-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0022_rename_dealer_email_dealer_loction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='loction',
        ),
    ]
