# Generated by Django 5.0.2 on 2024-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_remove_dealer_loction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
