# Generated by Django 5.0.2 on 2024-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0024_dealer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
