# Generated by Django 5.0.2 on 2024-03-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0025_alter_dealer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
