# Generated by Django 5.0.2 on 2024-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0027_sell_product_bach_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='bach_number',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
