# Generated by Django 5.0.6 on 2024-06-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0029_add_new_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_num', models.IntegerField()),
                ('batch_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_New_Batch',
        ),
    ]
