                    Order_detail(
                        id=d.id,
                        dealer_id=d.dealer_id,
                        marketing_employee_id=d.marketing_employee_id,
                        office_employee_id=d.office_employee_id,
                        store_employee_id=d.store_employee_id,
                        product_id=d.product_id,
                        product_name=d.product_name,
                        category=d.category,
                        type=d.type,
                        order_filter=d.order_filter,
                        stock_status=d.stock_status,
                        ordered_date=d.ordered_date,
                        #set_date
                        date=set_date,
                        qty=d.qty,
                        price=d.price,
                        total_price=d.total_price
                            ).save()