# Generated by Django 5.0.6 on 2024-06-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_batch_delete_add_new_batch'),
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creted_by', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
            ],
        ),
    ]
