# Generated by Django 5.0.6 on 2024-06-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_batch_delete_add_new_batch'),
        ('qr_code', '0002_voucher_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Production'), ('2', 'Return')], max_length=50)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qr_code.qr_code')),
            ],
        ),
    ]
