# Generated by Django 5.0.6 on 2024-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0005_in_stock_tag_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_num',
            name='verify_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher_num',
            name='verify_status',
            field=models.IntegerField(null=True),
        ),
    ]
