# Generated by Django 5.0.6 on 2024-06-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_batch_delete_add_new_batch'),
        ('qr_code', '0008_rename_voucher_num_voucher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(null=True, unique=True)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('verify_status', models.IntegerField(null=True)),
                ('verify_date', models.DateTimeField(null=True)),
                ('verify_by', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.product')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qr_code.qr_code')),
                ('voucher', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='qr_code.voucher_name')),
            ],
        ),
    ]
