# Generated by Django 5.0.6 on 2024-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0009_out_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_stock',
            name='verify_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
