# Generated by Django 5.0.2 on 2024-03-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0013_dealer_admin_alter_dealer_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default=True, max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.dealer')),
                ('employee', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.product')),
            ],
        ),
    ]
