# Generated by Django 5.0.2 on 2024-03-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_dealer_admin_alter_dealer_employee'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='pending', max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('dealer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.dealer')),
                ('employee', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
            ],
        ),
    ]
