# Generated by Django 5.0.2 on 2024-03-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_price_cart_total_price_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='qty',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='marketing_employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='office_employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='store_employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
