# Generated by Django 5.0.2 on 2024-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_ordermaster_employee_remove_ordermaster_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
