# Generated by Django 5.0.2 on 2024-03-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermaster_order_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='status',
            field=models.IntegerField(choices=[('1', 'in stock'), ('0', 'out of stock')], default=0),
        ),
    ]
