# Generated by Django 5.0.2 on 2024-03-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_detail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='status',
            new_name='stock_status',
        ),
    ]
