# Generated by Django 5.0.2 on 2024-03-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_status_order_detail_stock_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='orderfilter',
            new_name='order_filter',
        ),
    ]
