# Generated by Django 5.0.2 on 2024-03-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_orderfilter_order_detail_order_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='marketing_employee_name',
            new_name='marketing_employee_id',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='office_employee_name',
            new_name='office_employee_id',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='store_employee_name',
            new_name='store_employee_id',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='marketing_employee_name',
            new_name='marketing_employee_id',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='office_employee_name',
            new_name='office_employee_id',
        ),
        migrations.RenameField(
            model_name='ordermaster',
            old_name='store_employee_name',
            new_name='store_employee_id',
        ),
    ]
