# Generated by Django 5.0.2 on 2024-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_marketing_employee_name_order_detail_marketing_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
