# Generated by Django 5.0.2 on 2024-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordermaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='tally_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='stock_status',
            field=models.IntegerField(choices=[('1', 'in stock'), ('0', 'out of stock'), ('2', 'cancel')], default=0),
        ),
    ]
